### ISSUE TITLE
"Configuration"+auto like is invalid

### ISSUE THREAD

**Issue by leadra** [blackstar0169/youtube-autolike-script#1]
**Describe the bug**
1."Configuration"Menu cannot appear，dimmed no menu
2.auto like is invalid

**Screenshots**
![image](https://github.com/user-attachments/assets/4bced959-e377-4dfd-8f73-c8e73e1dab8f)
**Environment (required):**
 - OS: win10
 Cent Browser- 版本 5.1.1130.129 (正式版本) (64 位元) (Portable) (Chromium 118.0.5993.159)
Google Chrome版本 131.0.6778.140 (正式版本) (64 位元)

**Additional context**

**Comment by blackstar0169** [comment]
Hi, thank you for your report. I've fixed the like and configuration error in 1.8. Can you close the issue when you've checked if it works for you too ?

**Comment by leadra** [comment]
非常感謝，成功了!
THANKS,AUTO LIKE!
